# -*- coding: utf-8 -*-

Calendar.find_or_create(:cid => 'jetlyzer@yahoo.co.jp')                                             # 無銭カレンダー
Calendar.find_or_create(:cid => 'jhqrtl9na3gev1vihqnpt3qvgo@group.calendar.google.com')             # ライブアイドルカレンダー
Calendar.find_or_create(:cid => 'tsukubatvevent@gmail.com')                                         # PigooLIVE
Calendar.find_or_create(:cid => 'bbvrqpohqa6k9mib9788pmk3ro@group.calendar.google.com')             # 北海道アイドルカレンダー
Calendar.find_or_create(:cid => 'i90cg2r2eot24hqtosvj97pdi8@group.calendar.google.com')             # 北海道アイドルカレンダー（道外イベント）
Calendar.find_or_create(:cid => 'siig2006@gmail.com')                                               # Sendai Idol Inteligence Guide
Calendar.find_or_create(:cid => 'j76ss5h9b2gu1hj3bn56r5jkec@group.calendar.google.com')             # NAGOYA 有銭
Calendar.find_or_create(:cid => 'pdne7f9gcavkl92dqoqv8ubou0@group.calendar.google.com')             # NAGOYA 無銭
Calendar.find_or_create(:cid => '9p0ilmeposq8gsnch5516l3qbg@group.calendar.google.com')             # NAGOYA 購入特典
Calendar.find_or_create(:cid => 'ipqrp3ma3m6trcb0vdlnmts6s0@group.calendar.google.com')             # 新潟アイドル・ゆるきゃらイベント
Calendar.find_or_create(:cid => 'musenkansai@yahoo.co.jp')                                          # 無銭カレンダー関西版
Calendar.find_or_create(:cid => 'yuukicalendar@gmail.com')                                          # フリーライブin関西
Calendar.find_or_create(:cid => 'wa.cclive@gmail.com')                                              # 和歌山＜ライヴ＞情報
Calendar.find_or_create(:cid => 'michio.hatakeyama@gmail.com')                                      # 広島アイドルカレンダー(仮)
Calendar.find_or_create(:cid => 'kagoshima.idol.schedule@gmail.com')                                # 鹿児島アイドルカレンダー
Calendar.find_or_create(:cid => 'egirlsavex@gmail.com')                                             # E-Girls(Dream / Happiness / FLOWER)
Calendar.find_or_create(:cid => 'kejhqccvfcmjoo1av1uc5kdebg@group.calendar.google.com')             # iDOL Street
Calendar.find_or_create(:cid => '12btduot8d9rnn0e1etcgbpd9g@group.calendar.google.com')             # スト生
Calendar.find_or_create(:cid => 'so18t7q52t2h02m3o2bgibfnd0@group.calendar.google.com')             # SUPER☆GiRLS
Calendar.find_or_create(:cid => '7f952eub7fmbv381tjdab47ep4@group.calendar.google.com')             # Cheeky Parade
Calendar.find_or_create(:cid => '8lq0tp8rjnougpopd03gc0neak@group.calendar.google.com')             # NMB48
Calendar.find_or_create(:cid => 'passpoch@gmail.com')                                               # PASSPO☆
Calendar.find_or_create(:cid => '3nsmu3fnu16qian6mu6eldgv30@group.calendar.google.com')             # Perfume
Calendar.find_or_create(:cid => '9ith09rouq7acii4cud1699gvc@group.calendar.google.com')             # THE ポッシボー
Calendar.find_or_create(:cid => 'idca.revue@gmail.com')                                             # アイドリング!!!ライブ
Calendar.find_or_create(:cid => 'idcal.event@gmail.com')                                            # アイドリング!!!イベント
Calendar.find_or_create(:cid => 'rgvsrc05kcae3mdob9ll2991mo@group.calendar.google.com')             # アフィリア・サーガ
Calendar.find_or_create(:cid => 'kitada-erica@shopro.co.jp')                                        # おはガールちゅ!ちゅ!ちゅ!
Calendar.find_or_create(:cid => 'moejapan.jp_6h11ibse0961uor7muvmcfsoss@group.calendar.google.com') # でんぱ組.inc
Calendar.find_or_create(:cid => '0jdnkvqarn9isiesr25omnrt1c@group.calendar.google.com')             # ハロー！プロジェクト イベント関係
Calendar.find_or_create(:cid => 'silver.immortality@gmail.com')                                     # モーニング娘。
Calendar.find_or_create(:cid => 'ptp0siimqf9nge4p62pee569u4@group.calendar.google.com')             # 9nine
Calendar.find_or_create(:cid => 'sei@nomake.jp')                                                    # 青SHUN学園
