# -*- coding: utf-8 -*-

Calendar.find_or_create(:cid => 'jetlyzer@yahoo.co.jp')                                              # 無銭カレンダー
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'jhqrtl9na3gev1vihqnpt3qvgo@group.calendar.google.com')              # ライブアイドルカレンダー
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'tsukubatvevent@gmail.com')                                          # PigooLIVE
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'bbvrqpohqa6k9mib9788pmk3ro@group.calendar.google.com')              # 北海道アイドルカレンダー
  .update(:area => 'hokkaido')
Calendar.find_or_create(:cid => 'i90cg2r2eot24hqtosvj97pdi8@group.calendar.google.com')              # 北海道アイドルカレンダー（道外イベント）
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'siig2006@gmail.com')                                                # Sendai Idol Inteligence Guide
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'j76ss5h9b2gu1hj3bn56r5jkec@group.calendar.google.com')              # NAGOYA 有銭
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'pdne7f9gcavkl92dqoqv8ubou0@group.calendar.google.com')              # NAGOYA 無銭
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => '9p0ilmeposq8gsnch5516l3qbg@group.calendar.google.com')              # NAGOYA 購入特典
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'ipqrp3ma3m6trcb0vdlnmts6s0@group.calendar.google.com')              # 新潟アイドル・ゆるきゃらイベント
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'musenkansai@yahoo.co.jp')                                           # 無銭カレンダー関西版
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'yuukicalendar@gmail.com')                                           # フリーライブin関西
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'wa.cclive@gmail.com')                                               # 和歌山＜ライヴ＞情報
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'michio.hatakeyama@gmail.com')                                       # 広島アイドルカレンダー(仮)
  .update(:area => 'chushi')
Calendar.find_or_create(:cid => 'kagoshima.idol.schedule@gmail.com')                                 # 鹿児島アイドルカレンダー
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'kejhqccvfcmjoo1av1uc5kdebg@group.calendar.google.com')              # iDOL Street
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '12btduot8d9rnn0e1etcgbpd9g@group.calendar.google.com')              # スト生
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'so18t7q52t2h02m3o2bgibfnd0@group.calendar.google.com')              # SUPER☆GiRLS
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '7f952eub7fmbv381tjdab47ep4@group.calendar.google.com')              # Cheeky Parade
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '8lq0tp8rjnougpopd03gc0neak@group.calendar.google.com')              # NMB48
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'passpoch@gmail.com')                                                # PASSPO☆
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '3nsmu3fnu16qian6mu6eldgv30@group.calendar.google.com')              # Perfume
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '9ith09rouq7acii4cud1699gvc@group.calendar.google.com')              # THE ポッシボー
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'idca.revue@gmail.com')                                              # アイドリング!!!ライブ
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'idcal.event@gmail.com')                                             # アイドリング!!!イベント
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'rgvsrc05kcae3mdob9ll2991mo@group.calendar.google.com')              # アフィリア・サーガ
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'kitada-erica@shopro.co.jp')                                         # おはガールちゅ!ちゅ!ちゅ!
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'moejapan.jp_6h11ibse0961uor7muvmcfsoss@group.calendar.google.com')  # でんぱ組.inc
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '0jdnkvqarn9isiesr25omnrt1c@group.calendar.google.com')              # ハロー！プロジェクト イベント関係
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'silver.immortality@gmail.com')                                      # モーニング娘。
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'ptp0siimqf9nge4p62pee569u4@group.calendar.google.com')              # 9nine
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'mercicoco.sapporo2012@gmail.com')                                   # MERCI♡COCO
  .update(:area => 'hokkaido')
Calendar.find_or_create(:cid => 'fruity@livepro.jp')                                                 # フルーティー
  .update(:area => 'hokkaido')
Calendar.find_or_create(:cid => 'jcklvi0749q6ao7b3vsvd01v50@group.calendar.google.com')              # フルーティー イベント
  .update(:area => 'hokkaido')
Calendar.find_or_create(:cid => 'whiwhigirls@gmail.com')                                             # ほいっぷ★Girls
  .update(:area => 'hokkaido')
Calendar.find_or_create(:cid => 'cosweet.info_d0he3q8jediijgp8rgltc71cl0@group.calendar.google.com') # B♭
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'cosweet.info_cnpv3ksi5js4sons73dmt1rjt0@group.calendar.google.com') # mImi
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'cosweet.info_bkidosqdsg2t6ker6inbas6e4o@group.calendar.google.com') # StepOne全体
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'cosweet.info_n1d9ajtfc586i1o8lpvsi2i8tc@group.calendar.google.com') # ドロシーリトルハッピー
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'cosweet.info_fi4ja5b4vboe147r7h2n8hd5s4@group.calendar.google.com') # ハッピーダンス・ロリポップ招幸群
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'cosweet.info_fcqgopguslnrivl7kkk2de1a1s@group.calendar.google.com') # Party Rockets
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'kdgr6hsa7ivk6dhu5t6gmkvds4425c6r@import.calendar.google.com')       # pramo
  .update(:area => 'tohoku')
Calendar.find_or_create(:cid => 'projectnicegirl@yahoo.co.jp')                                       # NICE GIRL PROJECT!
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'palet.staff7@gmail.com')                                            # palet
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'prediaparty@gmail.com')                                             # predia
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'idol.tip@gmail.com')                                                # Ｔ！Ｐ
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'idol.college.schedule@gmail.com')                                   # アイドルカレッジ
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'upupgirlsyotei@gmail.com')                                          # アップアップガールズ（仮）
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'eanhibmf6oaq6ponaj033a2rdo@group.calendar.google.com')              # ウルトラガール
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '6afmkg9bo7snfkkcjihhdup2po@group.calendar.google.com')              # ねがいごと
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'mages.co.jp_bdo50hchrduuuqjfdsrdvh665g@group.calendar.google.com')  # バックステージpass イベント出演情報
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'webmaster@rdmusic.jp')                                              # フラップガールズスクール
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => '7pfbnqqgl2l8glkbg2b95g4t84@group.calendar.google.com')              # ベイビーレイズ
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'kaitoro.official@gmail.com')                                        # 怪傑トロピカル丸
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'osusuperidolunit@gmail.com')                                        # OS☆U
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'ryutist.calender@gmail.com')                                        # RYUTist
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'info@versus-pro.com')                                               # しず風&絆〜KIZUNA〜,バーサスキッズ
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'cg5nafq5uajk5cene05afh39v8@group.calendar.google.com')              # チームしゃちほこ イベント
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'c8vn5k1reuntra4pvpr3so7tlo@group.calendar.google.com')              # チームしゃちほこ ツアー
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'pus29h8srv335r7qhcq07fdol8@group.calendar.google.com')              # オトメ☆コーポレーション
  .update(:area => 'chubu')
Calendar.find_or_create(:cid => 'cslioffice@gmail.com')                                              # Csli
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => '15cu5tfs01gge6jjrfmsist29s@group.calendar.google.com')              # Dancing Dolls
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'especia.official@gmail.com')                                        # Especia
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'frillfleur.cal@gmail.com')                                          # FrilL FleuR
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'jk21calendar@gmail.com')                                            # JK21
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'jsomessage@gmail.com')                                              # JSO
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'info@vress.jp')                                                     # Vress
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => 'n5vvpc0qf61ht2mbat01n0ppdg@group.calendar.google.com')              # いずこねこ
  .update(:area => 'kansai')
Calendar.find_or_create(:cid => '0ccc057smicju3saja50tr5n4g@group.calendar.google.com')              # ひめキュンフルーツ缶
  .update(:area => 'chushi')
Calendar.find_or_create(:cid => 'nvn5o0p6sk3dr6dgp7hpolpp5g@group.calendar.google.com')              # HR ライブ情報
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'loveinq.com_gs7s7pveear51p3pg9g8q0ptmc@group.calendar.google.com')  # LinQ イベントスケジュール
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'schedule@loveinq.com')                                              # LinQ 通常公演スケジュール
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'qunqun.asia_tc2iflfvhfbjd058nod9cf08dg@group.calendar.google.com')  # QunQun
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => '4up4nks06fe859aad3ap8klbo4@group.calendar.google.com')              # 流星群少女
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'sei@nomake.jp')                                                     # 青SHUN学園
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => '9jkan5p6oqqcq6hi3sc9ka8fvc@group.calendar.google.com')              # RYUKYU IDOL
  .update(:area => 'kyushu')
Calendar.find_or_create(:cid => 'tokyocheerparty604@gmail.com')                                      # トーキョーチアチアパーティー
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'rojmeftfbb1kmgo483s8l38gq0@group.calendar.google.com')              # ANNA☆S
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'trcallover@gmail.com')                                              # ALLOVER
  .update(:area => 'kanto')
Calendar.find_or_create(:cid => 'we.are.takeoff@gmail.com')                                          # TAKE OFF(テイクオフ)
  .update(:area => 'kansai')
